-- ============================================
-- Tabela: label_queue
-- Fila de etiquetas para impressão
-- ============================================

CREATE TABLE IF NOT EXISTS label_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id UUID NOT NULL,
    store_id BIGINT NOT NULL REFERENCES stores(id),
    product_id BIGINT NOT NULL REFERENCES products(id),
    variant_id BIGINT REFERENCES product_variants(id),
    quantity INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Índices
CREATE INDEX IF NOT EXISTS idx_label_queue_store ON label_queue(store_id);
CREATE INDEX IF NOT EXISTS idx_label_queue_tenant ON label_queue(tenant_id);

-- RLS
ALTER TABLE label_queue ENABLE ROW LEVEL SECURITY;

-- Policies (usando service_role, sem necessidade de policies restritivas no momento)
-- O acesso via admin client ignora RLS, mas criamos as policies para segurança

CREATE POLICY "Tenants can view own label queue"
ON label_queue FOR SELECT
USING (tenant_id = auth.uid());

CREATE POLICY "Tenants can insert to own label queue"
ON label_queue FOR INSERT
WITH CHECK (tenant_id = auth.uid());

CREATE POLICY "Tenants can update own label queue"
ON label_queue FOR UPDATE
USING (tenant_id = auth.uid());

CREATE POLICY "Tenants can delete from own label queue"
ON label_queue FOR DELETE
USING (tenant_id = auth.uid());
