CREATE TABLE IF NOT EXISTS optical_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    tenant_id UUID NOT NULL,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    evaluated_customer_id BIGINT NULL REFERENCES customers(id) ON DELETE SET NULL,
    evaluated_dependente_id BIGINT NULL REFERENCES dependentes(id) ON DELETE SET NULL,
    responsible_customer_id BIGINT NULL REFERENCES customers(id) ON DELETE SET NULL,
    imported_by_user_id UUID NULL,
    source_system TEXT NOT NULL DEFAULT 'manual',
    status TEXT NOT NULL DEFAULT 'rascunho',
    parse_status TEXT NOT NULL DEFAULT 'success',
    source_document_url TEXT NULL,
    source_document_host TEXT NULL,
    source_os_number TEXT NULL,
    source_exam_type TEXT NULL,
    source_exam_datetime TIMESTAMPTZ NULL,
    patient_name_raw TEXT NULL,
    evaluated_name_snapshot TEXT NULL,
    responsible_name_snapshot TEXT NULL,
    relationship_snapshot TEXT NULL,
    age_years INTEGER NULL,
    estilo_vida_uso_computador_horas INTEGER NULL,
    estilo_vida_dirigir_horas INTEGER NULL,
    estilo_vida_leitura_horas INTEGER NULL,
    estilo_vida_uso_celular_horas INTEGER NULL,
    estilo_vida_exposicao_sol_horas INTEGER NULL,
    estilo_vida_ambiente_interno_horas INTEGER NULL,
    estilo_vida_ambiente_externo_horas INTEGER NULL,
    estilo_vida_assistir_tv_horas INTEGER NULL,
    receita_longe_od_esferico TEXT NULL,
    receita_longe_od_cilindrico TEXT NULL,
    receita_longe_od_eixo TEXT NULL,
    receita_longe_oe_esferico TEXT NULL,
    receita_longe_oe_cilindrico TEXT NULL,
    receita_longe_oe_eixo TEXT NULL,
    receita_perto_od_esferico TEXT NULL,
    receita_perto_od_cilindrico TEXT NULL,
    receita_perto_od_eixo TEXT NULL,
    receita_perto_oe_esferico TEXT NULL,
    receita_perto_oe_cilindrico TEXT NULL,
    receita_perto_oe_eixo TEXT NULL,
    receita_adicao TEXT NULL,
    medida_dnp_od TEXT NULL,
    medida_dnp_oe TEXT NULL,
    medida_altura_od TEXT NULL,
    medida_altura_oe TEXT NULL,
    recommended_lens_name TEXT NULL,
    commercial_recommendation_raw TEXT NULL,
    extracted_text TEXT NULL,
    raw_payload_json JSONB NULL DEFAULT '{}'::jsonb,
    parse_warning TEXT NULL,
    document_hash TEXT NULL,
    exported_service_order_id BIGINT NULL REFERENCES service_orders(id) ON DELETE SET NULL,
    CONSTRAINT optical_evaluations_subject_check CHECK (
        (
            CASE WHEN evaluated_customer_id IS NULL THEN 0 ELSE 1 END +
            CASE WHEN evaluated_dependente_id IS NULL THEN 0 ELSE 1 END
        ) = 1
    ),
    CONSTRAINT optical_evaluations_source_system_check CHECK (
        source_system IN ('manual', 'ivision')
    ),
    CONSTRAINT optical_evaluations_status_check CHECK (
        status IN ('rascunho', 'concluida', 'importada', 'exportada')
    ),
    CONSTRAINT optical_evaluations_parse_status_check CHECK (
        parse_status IN ('success', 'partial', 'failed')
    )
);

CREATE INDEX IF NOT EXISTS idx_optical_evaluations_store_created_at
ON optical_evaluations(store_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_optical_evaluations_customer
ON optical_evaluations(store_id, evaluated_customer_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_optical_evaluations_dependente
ON optical_evaluations(store_id, evaluated_dependente_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_optical_evaluations_responsible
ON optical_evaluations(store_id, responsible_customer_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_optical_evaluations_source_os
ON optical_evaluations(store_id, source_os_number);

CREATE INDEX IF NOT EXISTS idx_optical_evaluations_document_hash
ON optical_evaluations(store_id, document_hash);

CREATE INDEX IF NOT EXISTS idx_optical_evaluations_age
ON optical_evaluations(store_id, age_years);
