-- Daily, auditable operational health snapshots. Apply through the existing
-- Supabase migration workflow before enabling the cron in production.

CREATE TABLE IF NOT EXISTS public.daily_store_health_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID NOT NULL,
  store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  report_date DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'ready' CHECK (status IN ('generating', 'ready', 'failed')),
  metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  alerts JSONB NOT NULL DEFAULT '[]'::jsonb,
  narrative TEXT NOT NULL DEFAULT '',
  source_failures JSONB NOT NULL DEFAULT '[]'::jsonb,
  generated_at TIMESTAMPTZ,
  generation_started_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (store_id, report_date)
);

CREATE INDEX IF NOT EXISTS daily_store_health_reports_store_date_idx
  ON public.daily_store_health_reports (store_id, report_date DESC);

CREATE TABLE IF NOT EXISTS public.daily_store_health_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID NOT NULL,
  store_id BIGINT NOT NULL UNIQUE REFERENCES public.stores(id) ON DELETE CASCADE,
  settings JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by_user_id UUID NULL
);

ALTER TABLE public.daily_store_health_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_store_health_settings ENABLE ROW LEVEL SECURITY;

-- The application reads and writes these records only through the service role.
