create table if not exists public.whatsapp_store_channels (
    id bigint generated by default as identity primary key,
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    store_id bigint not null references public.stores(id) on delete cascade,
    provider text not null default 'evolution',
    instance_key text not null,
    phone_number text not null,
    is_active boolean not null default false,
    connection_status text not null default 'unknown',
    last_connection_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint whatsapp_store_channels_provider_check check (provider in ('evolution')),
    constraint whatsapp_store_channels_connection_status_check
        check (connection_status in ('unknown', 'connecting', 'connected', 'disconnected')),
    constraint whatsapp_store_channels_store_unique unique (store_id, provider),
    constraint whatsapp_store_channels_instance_unique unique (provider, instance_key)
);

create table if not exists public.whatsapp_inbound_messages (
    id bigint generated by default as identity primary key,
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    store_id bigint not null references public.stores(id) on delete cascade,
    channel_id bigint not null references public.whatsapp_store_channels(id) on delete cascade,
    provider_message_id text not null,
    remote_phone text not null,
    message_text text,
    payload jsonb,
    status text not null default 'received',
    created_at timestamptz not null default now(),
    constraint whatsapp_inbound_messages_status_check
        check (status in ('received', 'ignored', 'processed', 'failed')),
    constraint whatsapp_inbound_messages_provider_id_unique
        unique (channel_id, provider_message_id)
);

create table if not exists public.whatsapp_outbound_messages (
    id bigint generated by default as identity primary key,
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    store_id bigint not null references public.stores(id) on delete cascade,
    channel_id bigint not null references public.whatsapp_store_channels(id) on delete cascade,
    inbound_message_id bigint references public.whatsapp_inbound_messages(id) on delete set null,
    provider_message_id text,
    remote_phone text not null,
    message_text text not null,
    message_type text not null default 'os_status',
    status text not null default 'pending',
    payload jsonb,
    error_message text,
    sent_at timestamptz,
    created_at timestamptz not null default now(),
    constraint whatsapp_outbound_messages_status_check
        check (status in ('pending', 'sent', 'failed', 'cancelled'))
);

create index if not exists idx_whatsapp_channels_store
    on public.whatsapp_store_channels(store_id);
create index if not exists idx_whatsapp_inbound_store_created
    on public.whatsapp_inbound_messages(store_id, created_at desc);
create index if not exists idx_whatsapp_outbound_store_created
    on public.whatsapp_outbound_messages(store_id, created_at desc);

alter table public.whatsapp_store_channels enable row level security;
alter table public.whatsapp_inbound_messages enable row level security;
alter table public.whatsapp_outbound_messages enable row level security;

comment on table public.whatsapp_store_channels is
    'Canal WhatsApp/Evolution configurado por loja.';
comment on table public.whatsapp_inbound_messages is
    'Auditoria e idempotencia das mensagens recebidas.';
comment on table public.whatsapp_outbound_messages is
    'Fila e auditoria das mensagens enviadas pelo canal WhatsApp.';
