import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const readSource = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('Sicredi Pix permanece limitado ao ambiente oficial de producao', () => {
  const source = readSource('src/lib/pix/sicredi-client.server.ts')

  assert.match(source, /const DEFAULT_PROD_BASE_URL = 'https:\/\/api-pix\.sicredi\.com\.br'/)
  assert.match(source, /normalizedConfiguredUrl !== DEFAULT_PROD_BASE_URL/)
  assert.match(source, /baseUrl: new URL\(normalizedConfiguredUrl\)/)
  assert.match(source, /SICREDI_PIX_PROD_CLIENT_ID/)
  assert.match(source, /SICREDI_PIX_PROD_CLIENT_SECRET/)
  assert.match(source, /SICREDI_PIX_PROD_CERT_PEM_BASE64/)
  assert.match(source, /SICREDI_PIX_PROD_KEY_PEM_BASE64/)
  assert.match(source, /SICREDI_PIX_PROD_CA_PEM_BASE64/)
  assert.match(source, /readSecretMaterial/)
  assert.doesNotMatch(source, /SICREDI_PIX_HML_/)
  assert.doesNotMatch(source, /process\.env\.client_id/)
  assert.doesNotMatch(source, /process\.env\.client_secret/)
})

test('cobranca Pix exige autorizacao, evita duplicidade e confere o Sicredi antes de recriar', () => {
  const client = readSource('src/lib/pix/sicredi-client.server.ts')
  const actions = readSource('src/lib/actions/pix-installment.actions.ts')
  const modal = readSource('src/components/modals/PixInstallmentChargeModal.tsx')
  const parcelas = readSource('src/components/financeiro/ParcelasInterface.tsx')
  const parcelaSearch = readSource('src/components/modals/ParcelaSearchModal.tsx')
  const financiamentoBox = readSource('src/components/vendas/FinanciamentoBox.tsx')
  const installmentPresentation = readSource('src/lib/pix/installment-charge-presentation.ts')
  const parcelasActions = readSource('src/lib/actions/parcelas.actions.ts')
  const salesActions = readSource('src/lib/actions/vendas.actions.ts')
  const receiptRules = readSource('src/lib/installment-balance.ts')
  const webhook = readSource('src/app/api/webhooks/sicredi/pix/route.ts')
  const migration = readSource('supabase/migrations/20260818140000_sicredi_pix_automatic_settlement.sql')
  const effectiveBalanceMigration = readSource('supabase/migrations/20260827170000_installment_receipt_effective_balance.sql')

  assert.match(actions, /await cancelSicrediImmediateCharge\(charge\.txid\)/)
  assert.doesNotMatch(actions, /getPixChargesForInstallments[\s\S]*?catch \{\s*return \{\}/)
  assert.match(actions, /verifyEmployeeAuthorization\(data\.authorizationToken/)
  assert.match(actions, /ensureSicrediIsAvailableBeforeChargeCreation/)
  assert.match(actions, /httpStatus === 408/)
  assert.match(actions, /httpStatus === 429/)
  assert.match(actions, /httpStatus >= 500/)
  assert.match(actions, /Nenhuma cobranca foi criada; tente novamente em alguns instantes/)
  assert.match(actions, /status: 'CREATING'/)
  assert.match(actions, /reconcileChargeWithSicredi/)
  assert.match(actions, /locallyExpired\.status === 'EXPIRED'/)
  assert.match(actions, /locallyExpired\.status !== 'ERROR'/)
  assert.match(actions, /error\.statusCode !== 404/)
  assert.match(actions, /recoverCreatingCharge/)
  assert.match(actions, /receive_installment_payment/)
  assert.match(actions, /settlement_idempotency_key/)
  assert.match(actions, /settlement_idempotency_key: randomUUID\(\)/)
  assert.match(actions, /getSettlementPaymentIds/)
  assert.match(actions, /export async function getPixInstallmentCharge/)
  assert.match(actions, /ainda esta sendo processado/)
  assert.match(actions, /remoteBeforeCancellation\.status === 'CONCLUIDA'[\s\S]*?settleConfirmedPixCharge/s)
  assert.match(actions, /if \(current\.status === 'PAID'\) \{[\s\S]*?return \{ success: true, data: serialized \}/)
  assert.match(actions, /latest\?\.status === 'PAID' && latest\.settlement_status !== 'COMPLETED'[\s\S]*?settleConfirmedPixCharge\(admin, latest\)/)
  assert.match(actions, /if \(row\.status === 'PAID'\)[\s\S]*?settleConfirmedPixCharge\(admin, row\)/)
  assert.match(actions, /update\(\{ status: 'EXPIRED'[\s\S]*?eq\('status', 'PENDING'\)/)
  assert.match(actions, /NOT_FOUND_CONFIRMATION_DELAY_MS/)
  assert.match(actions, /recovery_not_found_at/)
  assert.match(actions, /allocatableBalance/)
  assert.match(actions, /resolvedStrategy/)
  assert.match(actions, /processSicrediPixWebhookPayload/)
  assert.match(webhook, /processSicrediPixWebhookPayload/)
  assert.match(migration, /settlement_status/)
  assert.match(migration, /settlement_idempotency_key/)
  assert.match(actions, /SicrediPixHttpError.*statusCode !== 404/s)
  assert.match(client, /'GET' \| 'POST' \| 'PUT' \| 'PATCH'/)
  assert.match(client, /input\.txid \? 'PUT' : 'POST'/)
  assert.match(modal, /reconcileBeforeNewCharge/)
  assert.match(modal, /A cobranca expirada foi encerrada/)
  assert.match(modal, /Conferir situação do QR Code/)
  assert.match(modal, /A cobrança anterior não foi localizada/)
  assert.match(modal, /messagePrefix.*baixa concluida/s)
  assert.match(modal, /finishSettledCharge/)
  assert.match(modal, /settlementPaymentIds/)
  assert.match(modal, /getPixInstallmentCharge/)
  assert.match(modal, /const pollSicrediCharge = async \(\) =>/)
  assert.match(modal, /pollSicrediCharge[\s\S]*?refreshPixInstallmentCharge\(\{ storeId, chargeId: charge\.id \}\)/)
  assert.match(modal, /window\.setInterval\(\(\) => void pollSicrediCharge\(\), 5000\)/)
  assert.match(modal, /getDefaultPartialReceiptStrategy/)
  assert.match(modal, /Amortização extra/)
  assert.match(modal, /Recuperar geração/)
  assert.match(modal, /const authorizationToken = employee\.authorization_token/)
  assert.match(modal, /authorizationToken,/)
  assert.match(parcelasActions, /anexarStatusPix/)
  assert.match(parcelas, /QR Code gerado/)
  assert.match(parcelas, /Pix Sicredi/)
  assert.match(parcelasActions, /O relatorio deve apresentar o saldo atual/)
  assert.match(parcelasActions, /const valorAReceber = getInstallmentOutstanding\(parcela\)/)
  assert.doesNotMatch(parcelasActions, /valor_pago:\s*resumo\?\.total/)
  assert.match(parcelasActions, /valor_renegociado_saida/)
  assert.match(salesActions, /valor_renegociado_saida/)
  assert.match(salesActions, /financiamento_id: p\.financiamento_id/)
  assert.doesNotMatch(parcelasActions, /const firstSnapshot/)
  assert.match(modal, /shouldGenerateRemainingBalance/)
  assert.doesNotMatch(modal, /O Pix anterior foi baixado/)
  assert.match(parcelaSearch, /refreshSelectedClientData/)
  assert.match(parcelaSearch, /await refreshSelectedClientData\(\)/)
  assert.match(parcelaSearch, /hasNextInstallment=\{Boolean\(pixInstallment\.has_next_installment\)\}/)
  assert.match(parcelaSearch, /onSettled=\{async \(\) =>/)
  assert.match(financiamentoBox, /getPixInstallmentActionLabel/)
  assert.match(financiamentoBox, /shouldOpenExistingPixInstallmentCharge/)
  assert.match(installmentPresentation, /Conferir pagamento/)
  assert.match(installmentPresentation, /Conferir situação/)
  assert.match(receiptRules, /getInstallmentReceiptPreview/)
  assert.match(receiptRules, /getDefaultPartialReceiptStrategy/)
  assert.match(effectiveBalanceMigration, /create or replace function public\.receive_installment_payment_core/)
  assert.match(effectiveBalanceMigration, /coalesce\(v_origin\.valor_renegociado_saida, 0\)/)
  assert.match(effectiveBalanceMigration, /coalesce\(v_installment\.valor_renegociado_saida, 0\)/)
  assert.match(effectiveBalanceMigration, /valor_renegociado_saida = coalesce\(nullif\(v_snapshot->>'valor_renegociado_saida'/)
})

test('PDV Express protege baixa, estoque, replay e fila da maquininha', () => {
  const saleActions = readSource('src/lib/actions/pix-sale.actions.ts')
  const salesActions = readSource('src/lib/actions/vendas.actions.ts')
  const saleModal = readSource('src/components/modals/PixSaleChargeModal.tsx')
  const addPaymentForm = readSource('src/components/vendas/AddPagamentoForm.tsx')
  const experimentalSale = readSource('src/components/vendas/VendaInterfaceExperimental.tsx')
  const displayRoute = readSource('src/app/api/store/[storeId]/pix-display/route.ts')
  const displayClient = readSource('src/components/pix/PixMaquininhaClient.tsx')
  const displayGate = readSource('src/components/pix/PixMaquininhaAccessGate.tsx')
  const displayActions = readSource('src/lib/actions/pix-maquininha.actions.ts')
  const displayAccess = readSource('src/lib/pix/pix-maquininha-access.ts')
  const tabletPage = readSource('src/app/tablet/[storeId]/page.tsx')
  const machinePage = readSource('src/app/dashboard/loja/[storeId]/pix-maquininha/page.tsx')
  const safetyMigration = readSource('supabase/migrations/20260818160000_sicredi_pix_express_safety.sql')
  const paymentUniquenessScopeMigration = readSource('supabase/migrations/20260828100000_scope_pix_sale_payment_uniqueness.sql')
  const receiptPage = readSource('src/app/print/recibo/[id]/page.tsx')

  assert.match(saleActions, /settlement_idempotency_key/)
  assert.match(saleActions, /SICREDI_PIX_PROD_CHARGE_EXPIRATION_SECONDS/)
  assert.match(saleActions, /in\('obs', \[obs, legacyObs\]\)/)
  assert.match(saleActions, /eq\('status', 'CREATING'\)/)
  assert.match(saleActions, /CREATION_RECOVERY_DELAY_MS/)
  assert.match(saleActions, /latest\?\.status === 'PAID' && latest\.settlement_status !== 'COMPLETED'/)
  assert.match(saleActions, /if \(row\.status === 'PAID'\)/)
  assert.match(saleActions, /NOT_FOUND_CONFIRMATION_DELAY_MS/)
  assert.match(saleActions, /eq\('status', 'PENDING'\)\.select\('\*'\)\.maybeSingle\(\)/)
  assert.match(salesActions, /\^sale:\\d\+:\\d\+\\\.\\d\{2\}\$/)
  assert.match(saleModal, /Conferindo cobrança existente/)
  assert.match(saleModal, /Conferir pagamento/)
  assert.match(saleModal, /Gerar novo QR Code/)
  assert.match(saleModal, /getPixSaleCharge/)
  assert.match(saleModal, /const pollSicrediCharge = async \(\) =>/)
  assert.match(saleModal, /pollSicrediCharge[\s\S]*?refreshPixSaleCharge\(\{ storeId, chargeId: charge\.id \}\)/)
  assert.match(saleModal, /window\.setInterval\(\(\) => void pollSicrediCharge\(\), 5000\)/)
  assert.match(saleModal, /Pagamento confirmado automaticamente e registrado na venda/)
  assert.equal((saleModal.match(/export default function PixSaleChargeModal/g) || []).length, 1)
  assert.match(readSource('src/components/modals/PaymentModal.tsx'), /<PixSaleChargeModal/)
  assert.match(addPaymentForm, /<PixSaleChargeModal/)
  assert.match(saleModal, /z-\[120\]/)
  assert.match(saleModal, /requestCreationOnOpen/)
  assert.match(saleModal, /current\.status === 'PAID' && current\.settlementStatus === 'COMPLETED'/)
  assert.match(saleModal, /requestCreationOnOpen && canReplaceCurrent/)
  assert.match(saleModal, /onChargeChanged\?\.\(result\.data\)/)
  assert.match(saleModal, /setPendingOperation\('create'\)/)
  assert.match(readSource('src\/components\/modals\/EmployeeAuthModal.tsx'), /z-\[150\]/)
  assert.match(addPaymentForm, /getPixSaleCharge\(storeId, vendaId\)/)
  assert.match(addPaymentForm, /existe um Pix de R\$/)
  assert.match(addPaymentForm, /ACOMPANHAR PIX EXISTENTE/)
  assert.match(addPaymentForm, /setShouldCreatePixSale\(!hasActivePixSaleCharge\); setIsPixSaleModalOpen\(true\)/)
  assert.match(addPaymentForm, /requestCreationOnOpen=\{shouldCreatePixSale\}/)
  assert.match(addPaymentForm, /onPixSaleChargeChanged\?\.\(current\)/)
  assert.match(experimentalSale, /Pix de \{formatVendaCurrency\(pixSaleCharge\?\.amount\)\} aguardando pagamento/)
  assert.match(experimentalSale, /Acompanhar pagamento/)
  assert.match(experimentalSale, /onPixSaleChargeChanged=\{setPixSaleCharge\}/)
  assert.match(experimentalSale, /<PixSaleChargeModal/)
  assert.match(saleActions, /remainingAmount <= 0\.01/)
  assert.match(salesActions, /pix_express_creation_requests/)
  assert.match(salesActions, /createHash\('sha256'\)/)
  assert.match(salesActions, /export async function registrarSaidaVenda/)
  assert.match(salesActions, /related_venda_id: vendaId/)
  assert.match(displayRoute, /store\.tenant_id !== profile\.tenant_id/)
  assert.match(displayRoute, /isSicrediPilotStoreCnpj/)
  assert.match(displayRoute, /settings\.pix_provider !== 'sicredi'/)
  assert.match(displayRoute, /hasPixMachineGrant/)
  assert.doesNotMatch(displayRoute, /if \(!user\) return NextResponse\.json\(\{ message: 'Nao autenticado\.'/)
  assert.match(tabletPage, /isSicrediEnabled && <Link/)
  assert.match(machinePage, /isSicrediPilotStoreCnpj/)
  assert.match(displayRoute, /queuedCount/)
  assert.match(displayRoute, /clearedStatus/)
  assert.match(displayRoute, /const DISPLAY_WINDOW_MS = 30 \* 60 \* 1000/)
  assert.match(displayRoute, /saleResult\.error \|\| installmentResult\.error/)
  assert.match(displayClient, /Pagamento confirmado/)
  assert.match(displayClient, /QR Code indisponivel/)
  assert.match(displayClient, /displayError/)
  assert.match(displayClient, /Nao foi possivel carregar o Pix/)
  assert.match(displayGate, /Informe o PIN de um funcionario ativo/)
  assert.match(displayActions, /eq\('is_active', true\)/)
  assert.match(displayActions, /pixMachineCookieName/)
  assert.match(displayActions, /httpOnly: true/)
  assert.match(displayAccess, /timingSafeEqual/)
  assert.match(safetyMigration, /pix_express_creation_requests/)
  assert.match(safetyMigration, /pagamentos_pix_sicredi_venda_obs_idx/)
  assert.match(paymentUniquenessScopeMigration, /drop index if exists public\.pagamentos_pix_sicredi_venda_obs_idx/)
  assert.match(paymentUniquenessScopeMigration, /and parcela_id is null/)
  assert.match(receiptPage, /session\.auth\.getUser\(\)/)
  assert.match(receiptPage, /getProfileByAdmin\(user\.id\)/)
  assert.match(receiptPage, /eq\('tenant_id', profile\.tenant_id\)/)
  assert.match(receiptPage, /eq\('store_id', profile\.store_id\)/)
  assert.doesNotMatch(receiptPage, /pagamentosByVenda/)
})
