import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const readSource = (path) => readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')

test('Sicredi Pix permanece limitado ao ambiente oficial de producao', () => {
  const source = readSource('src/lib/pix/sicredi-client.server.ts')

  assert.match(source, /const DEFAULT_PROD_BASE_URL = 'https:\/\/api-pix\.sicredi\.com\.br'/)
  assert.match(source, /normalizedConfiguredUrl !== DEFAULT_PROD_BASE_URL/)
  assert.match(source, /baseUrl: new URL\(normalizedConfiguredUrl\)/)
  assert.match(source, /SICREDI_PIX_PROD_CLIENT_ID/)
  assert.match(source, /SICREDI_PIX_PROD_CLIENT_SECRET/)
  assert.match(source, /SICREDI_PIX_PROD_CERT_PEM_BASE64/)
  assert.match(source, /SICREDI_PIX_PROD_KEY_PEM_BASE64/)
  assert.match(source, /SICREDI_PIX_PROD_CA_PEM_BASE64/)
  assert.match(source, /readSecretMaterial/)
  assert.doesNotMatch(source, /SICREDI_PIX_HML_/)
  assert.doesNotMatch(source, /process\.env\.client_id/)
  assert.doesNotMatch(source, /process\.env\.client_secret/)
})

test('cobranca Pix exige autorizacao, evita duplicidade e confere o Sicredi antes de recriar', () => {
  const client = readSource('src/lib/pix/sicredi-client.server.ts')
  const actions = readSource('src/lib/actions/pix-installment.actions.ts')
  const modal = readSource('src/components/modals/PixInstallmentChargeModal.tsx')
  const parcelas = readSource('src/components/financeiro/ParcelasInterface.tsx')
  const parcelasActions = readSource('src/lib/actions/parcelas.actions.ts')
  const webhook = readSource('src/app/api/webhooks/sicredi/pix/route.ts')
  const migration = readSource('supabase/migrations/20260818140000_sicredi_pix_automatic_settlement.sql')

  assert.match(actions, /await cancelSicrediImmediateCharge\(charge\.txid\)/)
  assert.doesNotMatch(actions, /getPixChargesForInstallments[\s\S]*?catch \{\s*return \{\}/)
  assert.match(actions, /verifyEmployeeAuthorization\(data\.authorizationToken/)
  assert.match(actions, /status: 'CREATING'/)
  assert.match(actions, /reconcileChargeWithSicredi/)
  assert.match(actions, /locallyExpired\.status === 'EXPIRED'/)
  assert.match(actions, /locallyExpired\.status !== 'ERROR'/)
  assert.match(actions, /error\.statusCode !== 404/)
  assert.match(actions, /recoverCreatingCharge/)
  assert.match(actions, /receive_installment_payment/)
  assert.match(actions, /settlement_idempotency_key/)
  assert.match(actions, /settlement_idempotency_key: randomUUID\(\)/)
  assert.match(actions, /processSicrediPixWebhookPayload/)
  assert.match(webhook, /processSicrediPixWebhookPayload/)
  assert.match(migration, /settlement_status/)
  assert.match(migration, /settlement_idempotency_key/)
  assert.match(actions, /SicrediPixHttpError.*statusCode !== 404/s)
  assert.match(client, /'GET' \| 'POST' \| 'PUT' \| 'PATCH'/)
  assert.match(client, /input\.txid \? 'PUT' : 'POST'/)
  assert.match(modal, /reconcileBeforeNewCharge/)
  assert.match(modal, /A cobranca expirada foi encerrada/)
  assert.match(modal, /Verificar erro e gerar novo QR Code/)
  assert.match(modal, /Recuperar geração/)
  assert.match(modal, /const authorizationToken = employee\.authorization_token/)
  assert.match(modal, /authorizationToken,/)
  assert.match(parcelasActions, /anexarStatusPix/)
  assert.match(parcelas, /QR Code gerado/)
  assert.match(parcelas, /Quitado por Pix Sicredi/)
})

test('PDV Express protege baixa, estoque, replay e fila da maquininha', () => {
  const saleActions = readSource('src/lib/actions/pix-sale.actions.ts')
  const salesActions = readSource('src/lib/actions/vendas.actions.ts')
  const displayRoute = readSource('src/app/api/store/[storeId]/pix-display/route.ts')
  const displayClient = readSource('src/components/pix/PixMaquininhaClient.tsx')
  const safetyMigration = readSource('supabase/migrations/20260818160000_sicredi_pix_express_safety.sql')

  assert.match(saleActions, /settlement_idempotency_key/)
  assert.match(saleActions, /SICREDI_PIX_PROD_CHARGE_EXPIRATION_SECONDS/)
  assert.match(saleActions, /in\('obs', \[obs, legacyObs\]\)/)
  assert.match(saleActions, /eq\('status', 'CREATING'\)/)
  assert.match(saleActions, /CREATION_RECOVERY_DELAY_MS/)
  assert.match(salesActions, /pix_express_creation_requests/)
  assert.match(salesActions, /createHash\('sha256'\)/)
  assert.match(salesActions, /export async function registrarSaidaVenda/)
  assert.match(salesActions, /related_venda_id: vendaId/)
  assert.match(displayRoute, /store\.tenant_id !== profile\.tenant_id/)
  assert.match(displayRoute, /queuedCount/)
  assert.match(displayRoute, /clearedStatus/)
  assert.match(displayClient, /Pagamento confirmado/)
  assert.match(displayClient, /QR Code indisponivel/)
  assert.match(safetyMigration, /pix_express_creation_requests/)
  assert.match(safetyMigration, /pagamentos_pix_sicredi_venda_obs_idx/)
})
