'use strict'

const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('towerDesktop', {
  isAvailable: true,
  getNetworkStatus: () => ipcRenderer.invoke('tower:get-network-status'),
  openNetworkSettings: () => ipcRenderer.invoke('tower:open-network-settings'),
  getDeviceIdentity: () => ipcRenderer.invoke('tower:get-device-identity'),
  enrollAsset: (request) => ipcRenderer.invoke('tower:enroll-asset', request),
  getAssetIdentityStatus: () => ipcRenderer.invoke('tower:get-asset-identity-status'),
  pairDevice: (request) => ipcRenderer.invoke('tower:pair-device', request),
  getDeviceSessionStatus: () => ipcRenderer.invoke('tower:get-device-session-status'),
  getDeviceSessionSummary: () => ipcRenderer.invoke('tower:get-device-session-summary'),
  getAdminPinStatus: () => ipcRenderer.invoke('tower:get-admin-pin-status'),
  submitAdminPin: (request) => ipcRenderer.invoke('tower:submit-admin-pin', request),
  getRemoteConfigAccess: () => ipcRenderer.invoke('tower:get-remote-config-access'),
  rotateRemoteConfigAccess: () => ipcRenderer.invoke('tower:rotate-remote-config-access'),
  createLocalSession: (request) => ipcRenderer.invoke('tower:create-local-session', request),
  listLocalSessions: () => ipcRenderer.invoke('tower:list-local-sessions'),
  createLocalCustomer: (request) => ipcRenderer.invoke('tower:create-local-customer', request),
  linkLocalCustomer: (request) => ipcRenderer.invoke('tower:link-local-customer', request),
  getLocalCustomerStatus: (localCustomerId) => ipcRenderer.invoke('tower:get-local-customer-status', localCustomerId),
  closeLocalSession: (request) => ipcRenderer.invoke('tower:close-local-session', request),
  saveLocalMeasurement: (request) => ipcRenderer.invoke('tower:save-local-measurement', request),
  getLocalSyncStatus: () => ipcRenderer.invoke('tower:get-local-sync-status'),
  syncLocalNow: () => ipcRenderer.invoke('tower:sync-local-now'),
  getHardwareDiagnostics: () => ipcRenderer.invoke('tower:get-hardware-diagnostics'),
  getHardwareApprovalStatus: () => ipcRenderer.invoke('tower:get-hardware-approval-status'),
  approveHardwareTest: (request) => ipcRenderer.invoke('tower:approve-hardware-test', request),
  openCustomerDisplayTest: () => ipcRenderer.invoke('tower:open-customer-display-test'),
  closeCustomerDisplayTest: () => ipcRenderer.invoke('tower:close-customer-display-test'),
  openCustomerExperience: (url) => ipcRenderer.invoke('tower:open-customer-experience', url),
  closeCustomerExperience: () => ipcRenderer.invoke('tower:close-customer-experience'),
})
