create table if not exists public.whatsapp_customer_links (
    id bigint generated by default as identity primary key,
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    store_id bigint not null references public.stores(id) on delete cascade,
    channel_id bigint not null references public.whatsapp_store_channels(id) on delete cascade,
    remote_phone text not null,
    customer_id bigint not null references public.customers(id) on delete cascade,
    source text not null default 'phone_match',
    linked_at timestamptz not null default now(),
    last_confirmed_at timestamptz not null default now(),
    constraint whatsapp_customer_links_source_check
        check (source in ('phone_match', 'status_lookup', 'identifier_lookup', 'manual')),
    constraint whatsapp_customer_links_store_phone_unique
        unique (store_id, remote_phone)
);

create index if not exists idx_whatsapp_customer_links_store_customer
    on public.whatsapp_customer_links(store_id, customer_id);

alter table public.whatsapp_customer_links enable row level security;

comment on table public.whatsapp_customer_links is
    'Vinculo persistente entre telefone do WhatsApp e cliente da loja para a central operacional.';
