create table if not exists public.pix_installment_charges (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  store_id bigint not null references public.stores(id) on delete cascade,
  customer_id bigint references public.customers(id) on delete set null,
  venda_id bigint not null,
  financiamento_id bigint not null,
  installment_id bigint not null references public.financiamento_parcelas(id) on delete cascade,
  provider text not null default 'sicredi',
  txid text not null unique,
  status text not null default 'PENDING',
  amount numeric(14,2) not null check (amount > 0),
  interest_amount numeric(14,2) not null default 0 check (interest_amount >= 0),
  strategy text not null check (strategy in ('quitacao_total', 'baixa_parcial', 'somar_proxima')),
  pix_copy_paste text,
  location text,
  expires_at timestamptz,
  paid_at timestamptz,
  cancelled_at timestamptz,
  created_by_employee_id bigint references public.employees(id) on delete set null,
  created_by_user_id uuid,
  provider_response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pix_installment_charges_status_check
    check (status in ('CREATING', 'PENDING', 'PAID', 'EXPIRED', 'CANCELLED', 'DIVERGENT', 'ERROR'))
);

create unique index if not exists pix_installment_charges_one_pending_per_installment_idx
  on public.pix_installment_charges (installment_id)
  where status in ('CREATING', 'PENDING');

create index if not exists pix_installment_charges_store_status_idx
  on public.pix_installment_charges (store_id, status, created_at desc);

alter table public.pix_installment_charges enable row level security;

-- A tabela e acessada exclusivamente pelas actions do servidor usando service role.
-- Nenhuma policy direta para o cliente e criada deliberadamente.
