create table if not exists public.daily_health_data_quality_reviews (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  store_id bigint not null,
  issue_type text not null check (issue_type in ('duplicate_customer', 'duplicate_product')),
  fingerprint text not null,
  record_ids bigint[] not null default '{}',
  decision text not null check (decision in ('keep_separate', 'defer')),
  preferred_record_id bigint,
  deferred_until date,
  decided_by_user_id uuid,
  decided_by_employee_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, issue_type, fingerprint)
);

create index if not exists daily_health_data_quality_reviews_store_idx
  on public.daily_health_data_quality_reviews (store_id, issue_type, decision);

create table if not exists public.daily_health_data_quality_review_events (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  store_id bigint not null,
  issue_type text not null,
  fingerprint text,
  record_ids bigint[] not null default '{}',
  action text not null,
  before_data jsonb,
  after_data jsonb,
  actor_user_id uuid,
  actor_employee_id bigint,
  created_at timestamptz not null default now()
);

create index if not exists daily_health_data_quality_events_store_idx
  on public.daily_health_data_quality_review_events (store_id, created_at desc);

alter table public.daily_health_data_quality_reviews enable row level security;
alter table public.daily_health_data_quality_review_events enable row level security;

revoke all on table public.daily_health_data_quality_reviews from anon, authenticated;
revoke all on table public.daily_health_data_quality_review_events from anon, authenticated;
