create table if not exists public.whatsapp_webhook_events (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  store_id bigint not null references public.stores(id) on delete cascade,
  channel_id bigint not null references public.whatsapp_store_channels(id) on delete cascade,
  instance_key text not null,
  provider_message_id text not null,
  remote_phone text null,
  event_name text not null default 'messages.upsert',
  source text not null check (source in ('webhook', 'reconciliation')),
  provider_created_at timestamptz null,
  received_at timestamptz not null default now(),
  processing_status text not null default 'received'
    check (processing_status in ('received', 'forwarded', 'failed')),
  error_message text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (channel_id, provider_message_id)
);

create index if not exists idx_whatsapp_webhook_events_store_received
  on public.whatsapp_webhook_events(store_id, received_at desc);

alter table public.whatsapp_webhook_events enable row level security;

comment on table public.whatsapp_webhook_events is
  'Auditoria server-side dos eventos WhatsApp antes da classificacao e das recuperacoes por reconciliacao.';
