create table if not exists public.whatsapp_status_publications (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null,
  store_id bigint not null references public.stores(id) on delete cascade,
  channel_id bigint not null references public.whatsapp_store_channels(id) on delete cascade,
  provider_message_id text not null,
  message_text text,
  media_kind text,
  payload jsonb,
  published_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '24 hours'),
  created_at timestamptz not null default now(),
  constraint whatsapp_status_publications_channel_message_unique
    unique (channel_id, provider_message_id)
);

create index if not exists whatsapp_status_publications_active_idx
  on public.whatsapp_status_publications (channel_id, expires_at desc);

alter table public.whatsapp_status_publications enable row level security;

comment on table public.whatsapp_status_publications is
  'Status publicados pela loja no celular e capturados pelo webhook da Evolution.';
