BEGIN;

CREATE TABLE IF NOT EXISTS public.whatsapp_message_preferences (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  remote_phone TEXT NOT NULL,
  installment_reminders_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  installment_reminders_changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT whatsapp_message_preferences_store_phone_unique UNIQUE (store_id, remote_phone)
);

CREATE INDEX IF NOT EXISTS idx_whatsapp_message_preferences_installment_reminders
  ON public.whatsapp_message_preferences (store_id, installment_reminders_enabled)
  WHERE installment_reminders_enabled = FALSE;

ALTER TABLE public.whatsapp_message_preferences ENABLE ROW LEVEL SECURITY;

UPDATE public.stores
SET settings = jsonb_set(
  settings,
  '{whatsapp_automation,installment_due_reminder,template}',
  to_jsonb(
    (settings->'whatsapp_automation'->'installment_due_reminder'->>'template')
    || E'\n\nPara não receber mais lembretes de vencimento por WhatsApp, responda PARAR.'
  ),
  true
)
WHERE settings->'whatsapp_automation'->'installment_due_reminder'->>'template' IS NOT NULL
  AND settings->'whatsapp_automation'->'installment_due_reminder'->>'template' NOT ILIKE '%responda parar%';

COMMENT ON TABLE public.whatsapp_message_preferences IS
  'Preferências individuais de mensagens automáticas do WhatsApp por loja e telefone.';

COMMIT;
