begin;

-- Memoria do novo orquestrador. Estas tabelas sao independentes do estado
-- temporario usado pelo roteador legado, permitindo shadow mode sem alterar
-- quem responde ao cliente.
create table if not exists public.whatsapp_conversation_memory (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  store_id bigint not null references public.stores(id) on delete cascade,
  channel_id bigint not null references public.whatsapp_store_channels(id) on delete cascade,
  remote_phone text not null,
  mode text not null default 'shadow'
    check (mode in ('legacy', 'shadow', 'redesign')),
  summary jsonb not null default '{}'::jsonb,
  last_message_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (channel_id, remote_phone)
);

create table if not exists public.whatsapp_conversation_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id bigint not null references public.whatsapp_conversation_memory(id) on delete cascade,
  source_key text not null,
  provider_message_id text,
  role text not null
    check (role in ('customer', 'assistant', 'human', 'system')),
  message_kind text not null
    check (message_kind in ('text', 'image', 'document', 'audio', 'video', 'location', 'sticker', 'unknown')),
  message_text text,
  occurred_at timestamptz not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (conversation_id, source_key)
);

-- Um turno e a unidade de decisao produzida depois da curta janela de espera.
-- As mensagens continuam armazenadas separadamente e sao apenas relacionadas
-- ao turno, em vez de serem substituidas por um texto concatenado.
create table if not exists public.whatsapp_conversation_turns (
  id uuid primary key default gen_random_uuid(),
  conversation_id bigint not null references public.whatsapp_conversation_memory(id) on delete cascade,
  turn_key text not null,
  status text not null default 'collecting'
    check (status in ('collecting', 'ready', 'processing', 'processed', 'failed')),
  opened_at timestamptz not null,
  closes_at timestamptz not null,
  processed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (closes_at >= opened_at),
  unique (conversation_id, turn_key)
);

create table if not exists public.whatsapp_conversation_turn_messages (
  turn_id uuid not null references public.whatsapp_conversation_turns(id) on delete cascade,
  message_id uuid not null references public.whatsapp_conversation_messages(id) on delete restrict,
  position smallint not null check (position >= 0),
  primary key (turn_id, message_id),
  unique (turn_id, position)
);

create index if not exists idx_whatsapp_conversation_memory_store_updated
  on public.whatsapp_conversation_memory(store_id, updated_at desc);

create index if not exists idx_whatsapp_conversation_messages_recent
  on public.whatsapp_conversation_messages(conversation_id, occurred_at desc, created_at desc);

create index if not exists idx_whatsapp_conversation_messages_provider
  on public.whatsapp_conversation_messages(provider_message_id)
  where provider_message_id is not null;

create index if not exists idx_whatsapp_conversation_turns_open
  on public.whatsapp_conversation_turns(status, closes_at)
  where status in ('collecting', 'ready');

create or replace function public.touch_whatsapp_conversation_memory_from_message()
returns trigger
language plpgsql
as $$
begin
  update public.whatsapp_conversation_memory
  set
    last_message_at = greatest(coalesce(last_message_at, new.occurred_at), new.occurred_at),
    updated_at = now()
  where id = new.conversation_id;
  return new;
end;
$$;

drop trigger if exists whatsapp_conversation_messages_touch_memory
  on public.whatsapp_conversation_messages;
create trigger whatsapp_conversation_messages_touch_memory
after insert on public.whatsapp_conversation_messages
for each row execute function public.touch_whatsapp_conversation_memory_from_message();

create or replace function public.create_whatsapp_conversation_turn(
  p_conversation_id bigint,
  p_turn_key text,
  p_message_ids uuid[],
  p_opened_at timestamptz,
  p_closes_at timestamptz,
  p_metadata jsonb
)
returns uuid
language plpgsql
set search_path = public, pg_temp
as $$
declare
  v_turn_id uuid;
  v_expected_count integer;
  v_found_count integer;
  v_existing_message_ids uuid[];
begin
  if p_conversation_id is null or not exists (
    select 1 from public.whatsapp_conversation_memory where id = p_conversation_id
  ) then
    raise exception 'conversa do redesign nao localizada';
  end if;

  if nullif(trim(p_turn_key), '') is null or length(p_turn_key) > 300 then
    raise exception 'chave do turno invalida';
  end if;

  if p_opened_at is null or p_closes_at is null or p_closes_at < p_opened_at then
    raise exception 'janela temporal do turno invalida';
  end if;

  v_expected_count := coalesce(cardinality(p_message_ids), 0);
  if v_expected_count = 0 or v_expected_count > 50 then
    raise exception 'turno deve conter entre 1 e 50 mensagens';
  end if;

  if (select count(distinct message_id) from unnest(p_message_ids) message_id) <> v_expected_count then
    raise exception 'turno contem mensagens repetidas';
  end if;

  select count(*)
    into v_found_count
  from public.whatsapp_conversation_messages
  where conversation_id = p_conversation_id
    and id = any(p_message_ids);

  if v_found_count <> v_expected_count then
    raise exception 'turno contem mensagem ausente ou de outra conversa';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_conversation_id::text || ':' || p_turn_key, 0));

  select id
    into v_turn_id
  from public.whatsapp_conversation_turns
  where conversation_id = p_conversation_id
    and turn_key = p_turn_key;

  if found then
    select array_agg(message_id order by position)
      into v_existing_message_ids
    from public.whatsapp_conversation_turn_messages
    where turn_id = v_turn_id;

    if v_existing_message_ids is distinct from p_message_ids then
      raise exception 'chave do turno ja utilizada com outro conjunto de mensagens';
    end if;

    return v_turn_id;
  end if;

  insert into public.whatsapp_conversation_turns (
    conversation_id,
    turn_key,
    status,
    opened_at,
    closes_at,
    metadata
  ) values (
    p_conversation_id,
    trim(p_turn_key),
    'ready',
    p_opened_at,
    p_closes_at,
    coalesce(p_metadata, '{}'::jsonb)
  )
  returning id into v_turn_id;

  insert into public.whatsapp_conversation_turn_messages (turn_id, message_id, position)
  select v_turn_id, message_id, (ordinality - 1)::smallint
  from unnest(p_message_ids) with ordinality as ordered_messages(message_id, ordinality);

  return v_turn_id;
end;
$$;

revoke all on function public.create_whatsapp_conversation_turn(bigint, text, uuid[], timestamptz, timestamptz, jsonb)
  from public, anon, authenticated;
grant execute on function public.create_whatsapp_conversation_turn(bigint, text, uuid[], timestamptz, timestamptz, jsonb)
  to service_role;

alter table public.whatsapp_conversation_memory enable row level security;
alter table public.whatsapp_conversation_messages enable row level security;
alter table public.whatsapp_conversation_turns enable row level security;
alter table public.whatsapp_conversation_turn_messages enable row level security;

comment on table public.whatsapp_conversation_memory is
  'Resumo estruturado da conversa usado pelo novo orquestrador de WhatsApp.';
comment on table public.whatsapp_conversation_messages is
  'Mensagens literais individuais da memoria do novo orquestrador, sem conteudo binario.';
comment on table public.whatsapp_conversation_turns is
  'Janelas curtas de agrupamento usadas como unidade de decisao, sem fundir as mensagens originais.';

commit;
