-- Cobranças Pix Sicredi vinculadas diretamente a uma venda.
-- O pagamento só deve ser inserido em public.pagamentos após a confirmação do Sicredi.

create table if not exists public.pix_sale_charges (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  store_id bigint not null references public.stores(id) on delete cascade,
  venda_id bigint not null,
  customer_id bigint references public.customers(id) on delete set null,
  provider text not null default 'sicredi',
  txid text not null unique,
  status text not null default 'CREATING',
  amount numeric(14,2) not null check (amount > 0),
  pix_copy_paste text,
  location text,
  expires_at timestamptz,
  paid_at timestamptz,
  cancelled_at timestamptz,
  created_by_employee_id bigint references public.employees(id) on delete set null,
  created_by_user_id uuid,
  settlement_status text not null default 'PENDING',
  settlement_idempotency_key uuid not null default gen_random_uuid(),
  settlement_pagamento_id bigint references public.pagamentos(id) on delete set null,
  settled_at timestamptz,
  provider_response jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint pix_sale_charges_status_check
    check (status in ('CREATING', 'PENDING', 'PAID', 'EXPIRED', 'CANCELLED', 'ERROR')),
  constraint pix_sale_charges_settlement_status_check
    check (settlement_status in ('PENDING', 'COMPLETED', 'ERROR'))
);

create unique index if not exists pix_sale_charges_one_active_per_sale_idx
  on public.pix_sale_charges (venda_id)
  where status in ('CREATING', 'PENDING');

create unique index if not exists pix_sale_charges_settlement_key_idx
  on public.pix_sale_charges (settlement_idempotency_key);

create index if not exists pix_sale_charges_store_status_idx
  on public.pix_sale_charges (store_id, status, created_at desc);

alter table public.pix_sale_charges enable row level security;
