-- Agrupa todos os efeitos de um recebimento de parcela para permitir uma
-- reversao integral, auditavel e autorizada por gerente.
create table if not exists public.installment_receipt_operations (
  id bigint generated by default as identity primary key,
  tenant_id uuid not null references public.tenants(id),
  store_id bigint not null references public.stores(id),
  -- Mantidos sem FK para preservar a auditoria sem bloquear exclusoes futuras.
  financiamento_id bigint not null,
  venda_id bigint not null,
  customer_id bigint references public.customers(id) on delete set null,
  origin_installment_id bigint not null,
  received_amount numeric(14,2) not null,
  interest_amount numeric(14,2) not null default 0,
  payment_method text not null,
  strategy text not null,
  received_on date not null,
  received_by_employee_id bigint references public.employees(id) on delete set null,
  created_by_user_id uuid,
  installments_before jsonb not null,
  installments_after jsonb,
  sale_before jsonb not null,
  sale_after jsonb,
  payments_created jsonb not null default '[]'::jsonb,
  affected_installment_count integer not null default 1 check (affected_installment_count > 0),
  state text not null default 'pending' check (state in ('pending', 'completed', 'failed', 'reversed')),
  failure_message text,
  reversed_at timestamptz,
  reversed_by_employee_id bigint references public.employees(id) on delete set null,
  reversed_by_user_id uuid,
  reversal_reason text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists installment_receipt_operations_financing_idx
  on public.installment_receipt_operations (financiamento_id, created_at desc, id desc);

create index if not exists installment_receipt_operations_origin_idx
  on public.installment_receipt_operations (origin_installment_id)
  where state = 'completed' and reversed_at is null;

alter table public.pagamentos
  add column if not exists receipt_operation_id bigint
    references public.installment_receipt_operations(id) on delete set null;

create index if not exists pagamentos_receipt_operation_id_idx
  on public.pagamentos (receipt_operation_id)
  where receipt_operation_id is not null;

alter table public.installment_receipt_operations enable row level security;

-- A tabela e manipulada pelas actions do servidor usando a service role.
-- Nenhuma policy de acesso direto pelo cliente e criada deliberadamente.

create or replace function public.reverse_installment_receipt_operation(
  p_operation_id bigint,
  p_authorizing_employee_id bigint,
  p_user_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_operation public.installment_receipt_operations%rowtype;
  v_manager public.employees%rowtype;
  v_snapshot jsonb;
  v_newer_operation_id bigint;
  v_payment_ids jsonb;
begin
  if length(trim(coalesce(p_reason, ''))) < 5 then
    raise exception 'Informe um motivo com pelo menos 5 caracteres.';
  end if;

  select * into v_operation
  from public.installment_receipt_operations
  where id = p_operation_id
  for update;

  if not found then
    raise exception 'Operacao de recebimento nao encontrada.';
  end if;

  if v_operation.state <> 'completed' or v_operation.reversed_at is not null then
    raise exception 'Esta operacao nao esta disponivel para reversao.';
  end if;

  select * into v_manager
  from public.employees
  where id = p_authorizing_employee_id
    and store_id = v_operation.store_id
    and is_active = true
    and lower(role) = 'gerente';

  if not found then
    raise exception 'A reversao exige autorizacao de um gerente ativo da loja.';
  end if;

  select id into v_newer_operation_id
  from public.installment_receipt_operations
  where financiamento_id = v_operation.financiamento_id
    and state = 'completed'
    and reversed_at is null
    and (created_at, id) > (v_operation.created_at, v_operation.id)
  order by created_at desc, id desc
  limit 1;

  if v_newer_operation_id is not null then
    raise exception 'Reverta primeiro o recebimento mais recente deste carne.';
  end if;

  select coalesce(jsonb_agg(id order by id), '[]'::jsonb) into v_payment_ids
  from public.pagamentos
  where receipt_operation_id = v_operation.id;

  delete from public.pagamentos
  where receipt_operation_id = v_operation.id;

  -- Remove somente parcelas que nasceram nesta operacao. Parcelas originais
  -- nunca sao removidas pelo fluxo de recebimento.
  delete from public.financiamento_parcelas fp
  where fp.financiamento_id = v_operation.financiamento_id
    and exists (
      select 1
      from jsonb_array_elements(v_operation.installments_after) item
      where (item->>'id')::bigint = fp.id
    )
    and not exists (
      select 1
      from jsonb_array_elements(v_operation.installments_before) item
      where (item->>'id')::bigint = fp.id
    );

  for v_snapshot in
    select value from jsonb_array_elements(v_operation.installments_before)
  loop
    update public.financiamento_parcelas
    set numero_parcela = (v_snapshot->>'numero_parcela')::integer,
        data_vencimento = (v_snapshot->>'data_vencimento')::date,
        valor_parcela = (v_snapshot->>'valor_parcela')::numeric,
        valor_pago = nullif(v_snapshot->>'valor_pago', '')::numeric,
        data_pagamento = nullif(v_snapshot->>'data_pagamento', '')::date,
        status = v_snapshot->>'status',
        customer_id = nullif(v_snapshot->>'customer_id', '')::bigint,
        obs = v_snapshot->>'obs'
    where id = (v_snapshot->>'id')::bigint
      and financiamento_id = v_operation.financiamento_id;
  end loop;

  update public.vendas
  set valor_restante = nullif(v_operation.sale_before->>'valor_restante', '')::numeric,
      status = v_operation.sale_before->>'status',
      financiamento_id = nullif(v_operation.sale_before->>'financiamento_id', '')::bigint
  where id = v_operation.venda_id
    and store_id = v_operation.store_id;

  update public.installment_receipt_operations
  set state = 'reversed',
      reversed_at = now(),
      reversed_by_employee_id = p_authorizing_employee_id,
      reversed_by_user_id = p_user_id,
      reversal_reason = trim(p_reason)
  where id = v_operation.id;

  return jsonb_build_object(
    'operation_id', v_operation.id,
    'origin_installment_id', v_operation.origin_installment_id,
    'payment_ids', v_payment_ids
  );
end;
$$;

revoke all on function public.reverse_installment_receipt_operation(bigint, bigint, uuid, text) from public;
grant execute on function public.reverse_installment_receipt_operation(bigint, bigint, uuid, text) to service_role;

create or replace function public.reverse_legacy_exact_installment_receipt(
  p_installment_id bigint,
  p_authorizing_employee_id bigint,
  p_user_id uuid,
  p_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_installment public.financiamento_parcelas%rowtype;
  v_financing public.financiamento_loja%rowtype;
  v_sale public.vendas%rowtype;
  v_store public.stores%rowtype;
  v_manager public.employees%rowtype;
  v_payment public.pagamentos%rowtype;
  v_payment_count integer;
  v_installments_after jsonb;
  v_installments_before jsonb;
  v_sale_snapshot jsonb;
  v_operation_id bigint;
begin
  if length(trim(coalesce(p_reason, ''))) < 5 then
    raise exception 'Informe um motivo com pelo menos 5 caracteres.';
  end if;

  select * into v_installment
  from public.financiamento_parcelas
  where id = p_installment_id
  for update;

  if not found then raise exception 'Parcela nao encontrada.'; end if;

  select * into v_financing
  from public.financiamento_loja
  where id = v_installment.financiamento_id;
  if not found then raise exception 'Carne da parcela nao encontrado.'; end if;

  select * into v_sale from public.vendas where id = v_financing.venda_id;
  if not found then raise exception 'Venda da parcela nao encontrada.'; end if;
  select * into v_store from public.stores where id = v_installment.store_id;
  if not found or v_store.tenant_id is null then raise exception 'Loja da parcela sem empresa vinculada.'; end if;

  select * into v_manager
  from public.employees
  where id = p_authorizing_employee_id
    and store_id = v_installment.store_id
    and is_active = true
    and lower(role) = 'gerente';
  if not found then
    raise exception 'A reversao exige autorizacao de um gerente ativo da loja.';
  end if;

  select count(*) into v_payment_count
  from public.pagamentos
  where parcela_id = v_installment.id
    and receipt_operation_id is null;

  if v_payment_count <> 1 then
    raise exception 'A parcela nao possui um unico pagamento legado elegivel.';
  end if;

  select * into v_payment
  from public.pagamentos
  where parcela_id = v_installment.id
    and receipt_operation_id is null
  limit 1
  for update;

  if lower(coalesce(v_installment.status, '')) <> 'pago'
     or v_installment.data_pagamento is null
     or coalesce(v_payment.valor_pago, 0) <= 0
     or abs(v_payment.valor_pago - v_installment.valor_parcela) > 0.01
     or abs(v_payment.valor_pago - coalesce(v_installment.valor_pago, 0)) > 0.01 then
    raise exception 'O pagamento legado nao corresponde exatamente ao valor quitado da parcela.';
  end if;

  if exists (
    select 1
    from public.pagamentos newer
    join public.financiamento_parcelas newer_installment on newer_installment.id = newer.parcela_id
    where newer_installment.financiamento_id = v_installment.financiamento_id
      and newer.receipt_operation_id is null
      and (coalesce(newer.data_pagamento::date, newer.created_at::date), newer.id)
          > (coalesce(v_payment.data_pagamento::date, v_payment.created_at::date), v_payment.id)
  ) then
    raise exception 'Reverta primeiro o pagamento legado mais recente deste carne.';
  end if;

  if exists (
    select 1
    from public.pagamentos sibling
    join public.financiamento_parcelas sibling_installment on sibling_installment.id = sibling.parcela_id
    where sibling_installment.financiamento_id = v_installment.financiamento_id
      and sibling.parcela_id <> v_installment.id
      and sibling.receipt_operation_id is null
      and sibling.venda_id = v_payment.venda_id
      and coalesce(sibling.data_pagamento::date, sibling.created_at::date)
          = coalesce(v_payment.data_pagamento::date, v_payment.created_at::date)
      and sibling.employee_id is not distinct from v_payment.employee_id
      and sibling.created_by_user_id is not distinct from v_payment.created_by_user_id
      and lower(trim(coalesce(sibling.forma_pagamento, '')))
          = lower(trim(coalesce(v_payment.forma_pagamento, '')))
  ) then
    raise exception 'Foram encontrados pagamentos relacionados em outras parcelas; a reversao legada foi bloqueada.';
  end if;

  select jsonb_agg(to_jsonb(fp) order by fp.id) into v_installments_after
  from public.financiamento_parcelas fp
  where fp.financiamento_id = v_installment.financiamento_id;

  select jsonb_agg(
    case when fp.id = v_installment.id
      then to_jsonb(fp) || jsonb_build_object('status', 'Pendente', 'valor_pago', 0, 'data_pagamento', null)
      else to_jsonb(fp)
    end
    order by fp.id
  ) into v_installments_before
  from public.financiamento_parcelas fp
  where fp.financiamento_id = v_installment.financiamento_id;

  v_sale_snapshot := jsonb_build_object(
    'id', v_sale.id,
    'valor_restante', case when v_sale.is_historical_import is true
      then coalesce(v_sale.valor_restante, 0) + v_payment.valor_pago
      else v_sale.valor_restante end,
    'status', case when v_sale.is_historical_import is true then 'Fechada' else v_sale.status end,
    'financiamento_id', v_sale.financiamento_id
  );

  insert into public.installment_receipt_operations (
    tenant_id, store_id, financiamento_id, venda_id, customer_id,
    origin_installment_id, received_amount, interest_amount, payment_method,
    strategy, received_on, received_by_employee_id, created_by_user_id,
    installments_before, installments_after, sale_before, sale_after,
    payments_created, affected_installment_count, state, completed_at,
    reversed_at, reversed_by_employee_id, reversed_by_user_id, reversal_reason,
    created_at
  ) values (
    coalesce(v_installment.tenant_id, v_financing.tenant_id, v_store.tenant_id),
    v_installment.store_id, v_installment.financiamento_id, v_financing.venda_id,
    v_installment.customer_id, v_installment.id, v_payment.valor_pago, 0,
    coalesce(v_payment.forma_pagamento, 'Nao informado'), 'legacy_exact',
    coalesce(v_payment.data_pagamento::date, v_payment.created_at::date),
    v_payment.employee_id, v_payment.created_by_user_id, v_installments_before,
    v_installments_after, v_sale_snapshot, v_sale_snapshot,
    jsonb_build_array(to_jsonb(v_payment)), 1, 'reversed', now(), now(),
    p_authorizing_employee_id, p_user_id, trim(p_reason), v_payment.created_at
  ) returning id into v_operation_id;

  delete from public.pagamentos where id = v_payment.id;

  update public.financiamento_parcelas
  set status = 'Pendente', valor_pago = 0, data_pagamento = null
  where id = v_installment.id;

  return jsonb_build_object(
    'operation_id', v_operation_id,
    'origin_installment_id', v_installment.id,
    'payment_id', v_payment.id
  );
end;
$$;

revoke all on function public.reverse_legacy_exact_installment_receipt(bigint, bigint, uuid, text) from public;
grant execute on function public.reverse_legacy_exact_installment_receipt(bigint, bigint, uuid, text) to service_role;
