create table if not exists public.whatsapp_installment_reminders (
    id bigint generated by default as identity primary key,
    tenant_id uuid not null references public.tenants(id) on delete cascade,
    store_id bigint not null references public.stores(id) on delete cascade,
    channel_id bigint not null references public.whatsapp_store_channels(id) on delete cascade,
    installment_id bigint not null references public.financiamento_parcelas(id) on delete cascade,
    customer_id bigint not null references public.customers(id) on delete cascade,
    remote_phone text not null,
    due_date date not null,
    scheduled_for timestamptz not null,
    status text not null default 'scheduled',
    message_text text not null,
    payload jsonb,
    outbound_message_id bigint references public.whatsapp_outbound_messages(id) on delete set null,
    error_message text,
    sent_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint whatsapp_installment_reminders_status_check
        check (status in ('scheduled', 'sending', 'sent', 'failed', 'cancelled')),
    constraint whatsapp_installment_reminders_channel_installment_unique
        unique (channel_id, installment_id)
);

create index if not exists idx_whatsapp_installment_reminders_status_schedule
    on public.whatsapp_installment_reminders(status, scheduled_for);

create index if not exists idx_whatsapp_installment_reminders_store_due
    on public.whatsapp_installment_reminders(store_id, due_date);

alter table public.whatsapp_installment_reminders enable row level security;

comment on table public.whatsapp_installment_reminders is
    'Fila de lembretes de vencimento do WhatsApp. Cada parcela gera no maximo um disparo automatico por canal.';
