BEGIN;

ALTER TABLE public.post_sales_interactions
  ALTER COLUMN registrado_por_id DROP NOT NULL;

CREATE TABLE IF NOT EXISTS public.whatsapp_post_sale_followups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id UUID NOT NULL,
  store_id BIGINT NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  channel_id BIGINT NOT NULL REFERENCES public.whatsapp_store_channels(id) ON DELETE CASCADE,
  service_order_id BIGINT NOT NULL REFERENCES public.service_orders(id) ON DELETE CASCADE,
  customer_id BIGINT NOT NULL REFERENCES public.customers(id) ON DELETE CASCADE,
  post_sales_id BIGINT REFERENCES public.post_sales(id) ON DELETE SET NULL,
  remote_phone TEXT NOT NULL,
  delivered_at DATE NOT NULL,
  scheduled_for TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'scheduled',
  message_text TEXT NOT NULL,
  outbound_message_id BIGINT REFERENCES public.whatsapp_outbound_messages(id) ON DELETE SET NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_message TEXT,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT whatsapp_post_sale_followups_status_check
    CHECK (status IN ('scheduled', 'sending', 'sent', 'failed', 'cancelled')),
  CONSTRAINT whatsapp_post_sale_followups_service_order_unique
    UNIQUE (service_order_id)
);

CREATE INDEX IF NOT EXISTS idx_whatsapp_post_sale_followups_status_schedule
  ON public.whatsapp_post_sale_followups(status, scheduled_for);

CREATE INDEX IF NOT EXISTS idx_whatsapp_post_sale_followups_store_delivered
  ON public.whatsapp_post_sale_followups(store_id, delivered_at);

ALTER TABLE public.whatsapp_post_sale_followups ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.whatsapp_post_sale_followups IS
  'Fila de follow-up automatico de pos-venda por OS. Cada OS recebe no maximo um primeiro disparo automatico.';

COMMIT;
