-- Garantias adicionais para o fluxo Pix no PDV Express.
-- A chave da autorizacao e armazenada apenas como hash para tornar o retry
-- da mesma tentativa idempotente sem guardar o token HMAC.

create table if not exists public.pix_express_creation_requests (
  id bigint generated by default as identity primary key,
  token_hash text not null unique,
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  store_id bigint not null references public.stores(id) on delete cascade,
  venda_id bigint not null,
  employee_id bigint references public.employees(id) on delete set null,
  created_by_user_id uuid,
  created_at timestamptz not null default now()
);

create index if not exists pix_express_creation_requests_store_created_idx
  on public.pix_express_creation_requests (store_id, created_at desc);

alter table public.pix_express_creation_requests enable row level security;

-- Uma mesma venda nao pode receber duas baixas Pix Sicredi concorrentes.
create unique index if not exists pagamentos_pix_sicredi_venda_obs_idx
  on public.pagamentos (venda_id, obs)
  where forma_pagamento = 'Pix Sicredi' and obs is not null;
